id: D49BC73C1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-07T13:48:37+00:00'
last_modified: '2022-05-26T10:23:52.976381+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    98ad:
      image_group_id: I1PD95863
      title: བདུད་རྩི་འཁྱིལ་བའི་སྒྲུབ་ཐབས།
      total_pages: 1634
      order: 18
      base_file: 98ad.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
